name: 0.5-Create All, from Create AMI
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}
  AWS_SSH_PUBLIC_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SSH_PUBLIC_KEY }}

jobs:
  terraform_apply:
    name: Terraform Apply All
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Apply All
      run: |
        cd ./5-create-ami-optional
        terraform init
        terraform plan
        terraform apply -auto-approve
        cd ../6-create-ssl-certificate
        terraform init
        terraform plan
        terraform apply -auto-approve
        cd ../7-create-computing
        terraform init
        terraform plan
        terraform apply -auto-approve
        cd ../8.2-setup-rt53-cdn
        terraform init
        terraform plan
        terraform apply -auto-approve