name: Terraform Plan
on: push
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_CLI_ADMIN_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SECRET }}
  AWS_SSH_PUBLIC_KEY: ${{ secrets.AWS_DEV_CLI_ADMIN_SSH_PUBLIC_KEY }}

jobs:
  terraform_plan:
    name: Terraform Plan On Push
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    steps:
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1
    - name: Checkout
      uses: actions/checkout@v4      
    - name: Terraform plan
      run: |
        cd ./1-build-remote-state
        echo "######"
        printenv | grep AWS
        echo "######"
        terraform init
        terraform validate
        terraform plan