name: Terraform Apply
on: workflow_dispatch
env:
  AWS_AWS_DEV_CLI_ADMIN_KEY: ${{secrets.AWS_AWS_DEV_CLI_ADMIN_KEY}}
  AWS_DEV_CLI_ADMIN_SECRET: ${{secrets.AWS_DEV_CLI_ADMIN_SECRET}}
  AWS_DEV_CLI_ADMIN_SSH_PUBLIC_KEY: ${{secrets.AWS_DEV_CLI_ADMIN_SSH_PUBLIC_KEY}}

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Apply
      run: |
        terraform init
        terraform apply -auto-approve